# -*- coding: utf-8 -*-
"""HelloworldTensorFlow.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xvjGmKwZ9CefGzjPqhxSVQmHJNT0PJOu

1.1 - Building a Simple Neural Network
"""

import tensorflow as tf
import numpy as np
from tensorflow import keras

model = tf.keras.Sequential([keras.layers.Dense(units = 1, input_shape=[1])])

model.compile(optimizer="sgd",loss="mean_squared_error")

xs = np.array([-1,0,1,2,3,4], dtype = "float")
xy = np.array([-3,-1,1,3,5,7], dtype = "float")

model.fit(xs,xy, epochs = 1000)

print(model.predict([10]))

house_model = tf.keras.Sequential([keras.layers.Dense(units = 1, input_shape = [1])])

house_model.compile(optimizer = "sgd",loss= "mean_squared_error")

xvar = np.array([0,1,2,3,4,5,6], dtype = float)
yvar = np.array([50,100,150,200,250,300,350], dtype = float)

house_model.fit(xvar,yvar, epochs = 1000)

"""1.2"""
