# -*- coding: utf-8 -*-
"""Week2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jMz3gx6-IrL_XhX6pQeyfaBqB1tRJWBm

1.2 Introduction to Computer Vision
"""

import numpy as np
import tensorflow as tf
from tensorflow import keras

fashion_mnist = tf.keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

train_images, test_images = train_images/255.0, test_images/225.0

import matplotlib.pyplot as plt

index = 300

np.set_printoptions( linewidth = 320)
print(f'LABEL: {train_labels[index]}')
print(f'\nIMAGE PIXEL ARRAY:\n {train_images[index]}')

plt.imshow(train_images[index])

model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28,28)),
    keras.layers.Dense(128, activation = tf.nn.relu),
    keras.layers.Dense(10, activation = tf.nn.softmax )
])

model.compile(optimizer = tf.optimizers.Adam(), loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

model.fit(train_images,train_labels, epochs = 12)

model.evaluate(test_images, test_labels)
